/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_adasdead_WTools_wTerminal */

#ifndef _Included_me_adasdead_WTools_wTerminal
#define _Included_me_adasdead_WTools_wTerminal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_adasdead_WTools_wTerminal
 * Method:    write
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_me_adasdead_WTools_wTerminal_write
  (JNIEnv *, jclass, jstring);

/*
 * Class:     me_adasdead_WTools_wTerminal
 * Method:    writeLine
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_me_adasdead_WTools_wTerminal_writeLine
  (JNIEnv *, jclass, jstring);

/*
 * Class:     me_adasdead_WTools_wTerminal
 * Method:    setOutColor
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_me_adasdead_WTools_wTerminal_setOutColor
  (JNIEnv *, jclass, jshort);

/*
 * Class:     me_adasdead_WTools_wTerminal
 * Method:    resetColor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_me_adasdead_WTools_wTerminal_resetColor
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
