/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_adasdead_WTools_wSystem */

#ifndef _Included_me_adasdead_WTools_wSystem
#define _Included_me_adasdead_WTools_wSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_adasdead_WTools_wSystem
 * Method:    reboot
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_me_adasdead_WTools_wSystem_reboot
  (JNIEnv *, jclass);

/*
 * Class:     me_adasdead_WTools_wSystem
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_me_adasdead_WTools_wSystem_shutdown
  (JNIEnv *, jclass);

/*
 * Class:     me_adasdead_WTools_wSystem
 * Method:    _bsod
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_me_adasdead_WTools_wSystem__1bsod
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
