/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_adasdead_WTools_wNotifications */

#ifndef _Included_me_adasdead_WTools_wNotifications
#define _Included_me_adasdead_WTools_wNotifications
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_adasdead_WTools_wNotifications
 * Method:    notify
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_me_adasdead_WTools_wNotifications_notify
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
