/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_adasdead_WTools_wMouse */

#ifndef _Included_me_adasdead_WTools_wMouse
#define _Included_me_adasdead_WTools_wMouse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_adasdead_WTools_wMouse
 * Method:    click
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_me_adasdead_WTools_wMouse_click
  (JNIEnv *, jclass, jshort);

/*
 * Class:     me_adasdead_WTools_wMouse
 * Method:    _getPosition
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_me_adasdead_WTools_wMouse__1getPosition
  (JNIEnv *, jclass);

/*
 * Class:     me_adasdead_WTools_wMouse
 * Method:    setPosition
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_me_adasdead_WTools_wMouse_setPosition
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
